### ISSUE TITLE
Not clear on use of `import` statement

### ISSUE THREAD

**Issue by aneylon** [vitorlans/w3-css#2]
Can you provide further information or a link to examples of how the import would be used in either a react/ webpack implementation or something similar?
Thank you.

**Comment by vitorlans** [comment]
Hi, 

I've been using this module with react and webpack, so I add the import in my entry app, that where webpack will start to build.

My entry point, index.js
``` JS
import 'shared/styles/app.scss';
import 'w3-css/w3.css';

import React from 'react';
```

Webpack entry config.
``` JS
module.exports = {
  devtool: 'eval',

  entry: [
    require.resolve('./polyfills'),
    'webpack-hot-middleware/client',
    './src/web/index' <- here
  ],
```

so after that in my components I can use the classes supported by w3.css like this.

``` HTML
<div className="w3-theme w3-row w3-card-2 header--padding">
                        <div className="w3-col s2">
                            <LinkWidget className="w3-xxlarge" to='/account' ><i className="fa fa-user-circle-o" aria-hidden="true"></i></LinkWidget>
                        </div>
</div>
```

Thanks.

**Comment by aneylon** [comment]
I got it figured out.
https://github.com/aneylon/memory-games
Was thinking of putting together a small example project for people with no experience with css and style loaders. Would you be interested in adding an example to the package?

Thank you for putting this module together!
-Arlen
