### ISSUE TITLE
Question on lib

### ISSUE THREAD

**Issue by lesar** [vitorlans/w3-css#9]
Do you like if I do a PR to add  all colour library?  
[/lib/w3-colors-flat.css](https://www.w3schools.com/lib/w3-colors-flat.css)  
[/lib/w3-theme-indigo.css](https://www.w3schools.com/lib/w3-theme-indigo.css)  
...

**Comment by vitorlans** [comment]
Thank you @lesar 
But I don't believe it is a good idea,
because there are many lib (extensions) for w3css, it could be hard to keep update.
and generally you just add one theme, colors that you use in your apps.

**Comment by lesar** [comment]
Ok thank you @vitorlans 
I have write a bash script that download all files and put them in well structured folders on local linux pc.
If you change opinion let me know.
regards
